### PR TITLE
bug: Solved minor errors in paths for the installation scripts and services

### PR DESCRIPTION
**Pull request by reinarrow**
There were 2 minor errors in the installation methodologies.

### CODE REVIEW

**Comment by reinarrow** [comment]
Hey any news on this? I'd like the changes to be reviewed in order to keep contributing. I'm trying to set up my own moonboard led system.

**Comment by 8cH9azbsFifZ** [comment]
> Hey any news on this? I'd like the changes to be reviewed in order to keep contributing. I'm trying to set up my own moonboard led system.

Finally I found time to merge your pull requests :)

**Comment by reinarrow** [comment]
That's awesome, thank you. 

I wonder if you could please enable the issues in your repository settings so that we can further talk in there. I'm having an issue with Bluetooth packets that I would love to be able to discuss with you!

Best regards,
Lidia

**Comment by 8cH9azbsFifZ** [comment]
Done :)

**Pull request merged**
